
# navigation
[[main]]
name = "Homepage"
url = ""
weight = 1
# hasChildren = false

# [[main]]
# parent = "Homepage"
#name = "Homepage 2"
#url = "homepage/home-2/"

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 3